In [2]:
import pandas as pd

# Load dataset into a pandas dataframe
data = pd.read_csv('cars_class.csv')

In [3]:
data

,ID,Comp,Circ,D.Circ,Rad.Ra,Pr.Axis.Ra,Max.L.Ra,Scat.Ra,Elong,Pr.Axis.Rect,Max.L.Rect,Sc.Var.Maxis,Sc.Var.maxis,Ra.Gyr,Skew.Maxis,Skew.maxis,Kurt.maxis,Kurt.Maxis,Holl.Ra,Class
0,1,88,39,70,166,66,7,148,44,19,134,167,332,143,69,5,13,193,201,0
1,2,85,35,64,129,57,6,116,57,17,125,138,200,123,65,1,23,196,203,3
2,3,91,41,84,141,57,9,149,45,19,143,170,330,158,72,9,14,189,199,3
3,4,102,54,98,177,56,10,219,31,25,171,219,706,223,72,5,17,186,196,1
4,5,87,39,74,152,58,6,151,44,19,136,174,337,140,70,1,33,187,196,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714,715,111,58,105,183,51,6,265,26,29,174,285,1018,255,85,4,8,181,183,0
715,716,93,43,76,149,57,7,149,44,19,143,172,335,176,69,14,0,189,194,2
716,717,90,42,63,144,59,7,131,50,18,142,154,259,162,65,15,3,197,204,3
717,718,101,56,101,231,72,10,217,31,24,171,232,698,216,72,2,6,187,197,2
718,719,99,38,74,184,66,6,164,39,20,131,193,414,137,71,2,22,200,202,0

In [4]:
#deleting columns as per the dataset requirements
data.pop(data.columns[0])

0        1
1        2
2        3
3        4
4        5
      ...
714    715
715    716
716    717
717    718
718    719
Name: ID, Length: 719, dtype: int64

In [5]:
data

,Comp,Circ,D.Circ,Rad.Ra,Pr.Axis.Ra,Max.L.Ra,Scat.Ra,Elong,Pr.Axis.Rect,Max.L.Rect,Sc.Var.Maxis,Sc.Var.maxis,Ra.Gyr,Skew.Maxis,Skew.maxis,Kurt.maxis,Kurt.Maxis,Holl.Ra,Class
0,88,39,70,166,66,7,148,44,19,134,167,332,143,69,5,13,193,201,0
1,85,35,64,129,57,6,116,57,17,125,138,200,123,65,1,23,196,203,3
2,91,41,84,141,57,9,149,45,19,143,170,330,158,72,9,14,189,199,3
3,102,54,98,177,56,10,219,31,25,171,219,706,223,72,5,17,186,196,1
4,87,39,74,152,58,6,151,44,19,136,174,337,140,70,1,33,187,196,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714,111,58,105,183,51,6,265,26,29,174,285,1018,255,85,4,8,181,183,0
715,93,43,76,149,57,7,149,44,19,143,172,335,176,69,14,0,189,194,2
716,90,42,63,144,59,7,131,50,18,142,154,259,162,65,15,3,197,204,3
717,101,56,101,231,72,10,217,31,24,171,232,698,216,72,2,6,187,197,2
718,99,38,74,184,66,6,164,39,20,131,193,414,137,71,2,22,200,202,0

In [6]:
from sklearn.model_selection import train_test_split

# Split the data into training and test sets
train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)

In [7]:
# View the first 5 rows of the dataset
data.head()

# Check the dimensions of the dataset
data.shape

# Check the data types of the columns
data.dtypes

# Check for missing values
data.isna().sum()

#Based on the above exploration, we can see that there are no missing values in the dataset. Now, let's proceed with data preprocessing.

Comp            0
Circ            0
D.Circ          0
Rad.Ra          0
Pr.Axis.Ra      0
Max.L.Ra        0
Scat.Ra         0
Elong           0
Pr.Axis.Rect    0
Max.L.Rect      0
Sc.Var.Maxis    0
Sc.Var.maxis    0
Ra.Gyr          0
Skew.Maxis      0
Skew.maxis      0
Kurt.maxis      0
Kurt.Maxis      0
Holl.Ra         0
Class           0
dtype: int64

In [8]:
# Drop any rows with missing values
train_data.dropna(inplace=True)
test_data.dropna(inplace=True)

# Split the data into input features and target variable
X_train = train_data.iloc[:, :-1]
y_train = train_data.iloc[:, -1]
X_test = test_data.iloc[:, :-1]
y_test = test_data.iloc[:, -1]

# Standardize the data using StandardScaler
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
"""We will try the following classifiers:"""

"""Logistic Regression
Decision Tree Classifier
Random Forest Classifier
Support Vector Classifier (SVC)
K-Nearest Neighbors (KNN) Classifier"""

'Logistic Regression\nDecision Tree Classifier\nRandom Forest Classifier\nSupport Vector Classifier (SVC)\nK-Nearest Neighbors (KNN) Classifier'

In [10]:
# Import required classifiers and metrics
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

# Define the classifiers
lr = LogisticRegression(random_state=42)
dt = DecisionTreeClassifier(random_state=42)
rf = RandomForestClassifier(random_state=42)
svc = SVC(random_state=42)
knn = KNeighborsClassifier()

# Fit the classifiers on the training set
lr.fit(X_train, y_train)
dt.fit(X_train, y_train)
rf.fit(X_train, y_train)
svc.fit(X_train, y_train)
knn.fit(X_train, y_train)

# Predict the target variable on the test set
y_pred_lr = lr.predict(X_test)
y_pred_dt = dt.predict(X_test)
y_pred_rf = rf.predict(X_test)
y_pred_svc = svc.predict(X_test)
y_pred_knn = knn.predict(X_test)

# Evaluate the performance of the classifiers
print("Accuracy Scores:")
print("Logistic Regression: ", accuracy_score(y_test, y_pred_lr))
print("Decision Tree: ", accuracy_score(y_test, y_pred_dt))
print("Random Forest: ", accuracy_score(y_test, y_pred_rf))
print("SVC: ", accuracy_score(y_test, y_pred_svc))
print("KNN: ", accuracy_score(y_test, y_pred_knn))

print("\nF1 Scores:")
print("Logistic Regression: ", f1_score(y_test, y_pred_lr, average='macro'))
print("Decision Tree:", f1_score(y_test, y_pred_dt, average='macro'))
print("Random Forest: ", f1_score(y_test, y_pred_rf, average='macro'))
print("SVC: ", f1_score(y_test, y_pred_svc, average='macro'))
print("KNN: ", f1_score(y_test, y_pred_knn, average='macro'))

print("\nConfusion Matrices:")
print("Logistic Regression: \n", confusion_matrix(y_test, y_pred_lr))
print("Decision Tree: \n", confusion_matrix(y_test, y_pred_dt))
print("Random Forest: \n", confusion_matrix(y_test, y_pred_rf))
print("SVC: \n", confusion_matrix(y_test, y_pred_svc))
print("KNN: \n", confusion_matrix(y_test, y_pred_knn))

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Accuracy Scores:
Logistic Regression:  0.7777777777777778
Decision Tree:  0.7361111111111112
Random Forest:  0.7222222222222222
SVC:  0.7708333333333334
KNN:  0.7430555555555556

F1 Scores:
Logistic Regression:  0.7767978477358454
Decision Tree: 0.7235385825645426
Random Forest:  0.7137429403989426
SVC:  0.7692296918767507
KNN:  0.739265873015873

Confusion Matrices:
Logistic Regression:
 [[34  0  0  1]
 [ 1 19 19  1]
 [ 1  8 24  1]
 [ 0  0  0 35]]
Decision Tree:
 [[32  0  1  2]
 [ 4 25 10  1]
 [ 4 14 14  2]
 [ 0  0  0 35]]
Random Forest:
 [[34  0  0  1]
 [ 1 21 16  2]
 [ 3 15 14  2]
 [ 0  0  0 35]]
SVC:
 [[34  0  0  1]
 [ 0 19 18  3]
 [ 1  9 23  1]
 [ 0  0  0 35]]
KNN:
 [[34  0  0  1]
 [ 3 17 18  2]
 [ 2  6 25  1]
 [ 1  0  3 31]]

In [14]:

#Based on the evaluation metrics, we can see that Logistic Regression has the highest accuracy and F1-score. 
#Therefore, we will choose Random Forest Classifier as our final model and tune its hyperparameters.

In [15]:
# Set the final model as Logistic Regression
final_model = lr

# Fit the final model on the training set
final_model.fit(X_train, y_train)

# Predict the target variable on the test set
y_pred_final = final_model.predict(X_test)

# Evaluate the performance of the final model
print("Accuracy: ", accuracy_score(y_test, y_pred_final))
print("F1 Score: ", f1_score(y_test, y_pred_final, average='macro'))
print("\nConfusion Matrix: \n", confusion_matrix(y_test, y_pred_final))

Accuracy:  0.7777777777777778
F1 Score:  0.7767978477358454

Confusion Matrix:
 [[34  0  0  1]
 [ 1 19 19  1]
 [ 1  8 24  1]
 [ 0  0  0 35]]

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(